// Parity test: C++ UniPCScheduler vs tools/golden/unipc_traj.npz (generated by
// tools/golden/unipc_ref.py). Same fake model v(x,t)=0.1*sin(x+t), same x0.
#include "sampler/unipc.h"
#include "test_support/npz.h"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <stdexcept>
#include <string>
#include <vector>

int main() {
  try {
    auto g = sd::load_npz("tools/golden/unipc_traj.npz");
    const size_t n = 8;
    const int steps = 10;

    sd::UniPCScheduler sched(1000);
    sched.set_timesteps(steps, 5.0);
    if ((int)sched.sigmas().size() != steps + 1 ||
        sched.sigmas().size() != (size_t)g.at("sigmas").numel())
      throw std::runtime_error("sigma schedule size mismatch");

    double sig_diff = 0;
    const float* gs = g.at("sigmas").ptr<float>();
    for (size_t i = 0; i < sched.sigmas().size(); ++i)
      sig_diff = std::max(sig_diff, std::fabs((double)gs[i] - (double)sched.sigmas()[i]));

    std::vector<float> x(g.at("x0").ptr<float>(), g.at("x0").ptr<float>() + n);

    std::vector<float> mo(n), out(n);
    double worst = 0;
    int worst_step = -1;
    for (int i = 0; i < steps; ++i) {
      int64_t t = sched.timesteps()[(size_t)i];
      for (size_t j = 0; j < n; ++j)
        mo[j] = (float)(0.1 * std::sin((double)x[j] + (double)t));
      sched.step(mo.data(), t, x.data(), out.data(), n);
      const auto& ref = g.at("s" + std::to_string(i));
      if ((size_t)ref.numel() != n)
        throw std::runtime_error("bad npz entry s" + std::to_string(i));
      const float* r = ref.ptr<float>();
      double d = 0;
      for (size_t j = 0; j < n; ++j)
        d = std::max(d, std::fabs((double)r[j] - (double)out[j]));
      std::printf("step %2d: max|diff| = %.3e\n", i, d);
      if (d > worst) { worst = d; worst_step = i; }
      x = out;
    }
    std::printf("sigma schedule max diff: %.3e\n", sig_diff);
    std::printf("worst step %d: max abs diff %.3e (tol 1e-4)\n", worst_step, worst);
    if (!(worst < 1e-4)) { std::printf("FAIL\n"); return 1; }
    std::printf("PASS\n");
    return 0;
  } catch (const std::exception& e) {
    std::fprintf(stderr, "exception: %s\nFAIL\n", e.what());
    return 1;
  }
}
